routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['web', 'auth'])->group(function () {

	Route::get('profile', 'ProfileController@show')->name('profile');
	Route::put('profile', 'ProfileController@update');
	Route::get('profile/edit', 'ProfileController@edit');
	Route::delete('profile/image', 'ProfileController@remove');

	Route::get('account', 'AccountController@show')->name('account');
	Route::put('account', 'AccountController@update');
	Route::get('account/delete', 'AccountController@delete');
	Route::delete('account/delete', 'AccountController@destroy');
});

//Artikel
Route::resource('posts', 'PostController');
Route::get('posts/hapus/{id}', 'PostController@destroy')->name('posts.hapus');

//Kategori
Route::resource('category', 'CategoryController');
Route::get('/category/hapus/{id}', 'CategoryController@destroy')->name('category.hapus');

//Tags
Route::resource('tags', 'TagController');
Route::get('/tags/hapus/{id}', 'TagController@destroy')->name('tags.hapus');

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $table = 'tags';
    protected $fillable = [
        'name'
    ];
    public function posts(){
        return $this->belongsToMany('App\Post');
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use Illuminate\Http\Request;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tag = Tag::all();
        return view('tags.index', compact('tag'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required'
        ]);

        $tag = new Tag;
        $tag->name = $request->name;
        $tag->save();
        return redirect('/tags')->withInfo('Tag berhasil dibuat');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tag::find($id);
        return view('tags.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required'
        ]);

        $tag = Tag::find($id);
        $tag->name = $request->name;
        $tag->save();

        return redirect('/tags')->withInfo('Tag berhasil diedit');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tag = Tag::find($id);
        $tag->delete();

        return redirect('/tags')->withInfo('Tag berhasil dihapus');
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app')

{{-- @section('title', 'Buat Kategori Artikel') --}}
@section('content')
    <div class="container">
        <div class="card mt-4">
            <div class="card-header">
                <div class="text-center">Buat Tag Artikel</div>    
            </div>
            <div class="card-body">
                <form action="{{route('tags.store')}}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="title">Nama Tag</label>
                        <input type="text" name="name" class="form-control" placeholder="Nama Tag Artikel...">
                        {{-- validator --}}
                        @if($errors->has('name'))
                            <div class="text-danger">
                                {{$errors->first('name')}}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-success" value="Simpan">
                    </div>
                </form>    
        </div>    
    </div>
@endsection

resources/views/tags/edit.blade.php
@extends('layouts.app')

{{-- @section('title', 'Buat Kategori Artikel') --}}
@section('content')
    <div class="container">
        <div class="card mt-4">
            <div class="card-header">
                <div class="text-center">Edit Tag Artikel</div>    
            </div>
            <div class="card-body">
                <form action="{{route('tags.update', $tag->id)}}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="title">Nama Tag</label>
                        <input type="text" name="name" class="form-control" placeholder="Nama Tag Artikel..." value="{{$tag->name}}">
                        {{-- validator --}}
                        @if($errors->has('name'))
                            <div class="text-danger">
                                {{$errors->first('name')}}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-success" value="Simpan">
                    </div>
                </form>
            </div>    
        </div>    
    </div>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.app')

{{-- @section('title', 'Buat Kategori Artikel') --}}
@section('content')
    <div class="container">
        <div class="card mt-4">
            <div class="card-header">
                <div class="text-center">Tag Artikel</div>    
            </div>
            <div class="card-body">
                <a href="{{route('tags.create')}}" class="btn btn-primary">Buat Tag</a>
                <div class="text-center"><h4>List Tag</h4></div>
                <table class="table table-bordered table-hover table-striped" id="data-table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Tag</th>
                            <th>Tanggal Edit</th>
                            <th>Opsi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php
                            $i=1
                        @endphp
                        @foreach($tag as $t)
                            <tr>
                                <td>{{$i++}}</td>
                                <td>{{$t->name}}</td>
                                <td>{{date('j F Y', strtotime($t->updated_at))}}</td>
                                <td>
                                    <a href="{{route('tags.edit', $t->id)}}" class="btn btn-primary"><i class="fa fa-edit"></i> Edit</a>
                                    <a href="{{route('tags.hapus', $t->id)}}" class="btn btn-danger"><i class="fa fa-edit"></i> Hapus</a>
                                    {{-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editModal">
                                        <i class="fa fa-edit"></i> Edit
                                    </button>
                                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#hapusModal">
                                        <i class="fa fa-trash"></i> Hapus
                                    </button> --}}
                                </td>
                            </tr>
                        @endforeach   
                    </tbody>
                </table>
            </div>    
        </div>    
    </div>
@endsection