routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['web', 'auth'])->group(function () {

	Route::get('profile', 'ProfileController@show')->name('profile');
	Route::put('profile', 'ProfileController@update');
	Route::get('profile/edit', 'ProfileController@edit');
	Route::delete('profile/image', 'ProfileController@remove');

	Route::get('account', 'AccountController@show')->name('account');
	Route::put('account', 'AccountController@update');
	Route::get('account/delete', 'AccountController@delete');
	Route::delete('account/delete', 'AccountController@destroy');
});

//Artikel
Route::resource('posts', 'PostController');
Route::get('posts/hapus/{id}', 'PostController@destroy')->name('posts.hapus');

//Kategori
Route::resource('category', 'CategoryController');
Route::get('/category/hapus/{id}', 'CategoryController@destroy')->name('category.hapus');

//Tags
Route::resource('tags', 'TagController');
Route::get('/tags/hapus/{id}', 'TagController@destroy')->name('tags.hapus');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'categories';
    protected $fillable = [
        'name'
    ];
    public function posts(){
        return $this->hasMany('App\Post');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $category = Category::all();
        return view('category.index', compact('category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required'
        ]);

        $category = new Category;
        $category->name = $request->name;
        $category->save();
        
        return redirect('/category')->withInfo('Kategori berhasil dibuat');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required'
        ]);

        $category = Category::find($id);
        $category->name = $request->name;
        $category->save();

        return redirect('/category')->withInfo('Kategori berhasil diedit');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delete();
        return redirect('/category')->withInfo('Kategori berhasil dihapus');
        // return back()->withInfo('Kategori berhasil dihapus');
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')

{{-- @section('title', 'Buat Kategori Artikel') --}}
@section('content')
    <div class="container">
        <div class="card mt-4">
            <div class="card-header">
                <div class="text-center">Buat Kategori Artikel</div>    
            </div>
            <div class="card-body">
                <form action="{{route('category.store')}}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="title">Nama Kategori</label>
                        <input type="text" name="name" class="form-control" placeholder="Nama Kategori Artikel...">
                        {{-- validator --}}
                        @if($errors->has('name'))
                            <div class="text-danger">
                                {{$errors->first('name')}}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-success" value="Simpan">
                    </div>
                </form>    
        </div>    
    </div>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.app')

{{-- @section('title', 'Buat Kategori Artikel') --}}
@section('content')
    <div class="container">
        <div class="card mt-4">
            <div class="card-header">
                <div class="text-center">Edit Kategori Artikel</div>    
            </div>
            <div class="card-body">
                <form action="{{route('category.update', $category->id)}}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="title">Nama Kategori</label>
                        <input type="text" name="name" class="form-control" placeholder="Nama Kategori Artikel..." value="{{$category->name}}">
                        {{-- validator --}}
                        @if($errors->has('name'))
                            <div class="text-danger">
                                {{$errors->first('name')}}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-success" value="Simpan">
                    </div>
                </form>
            </div>    
        </div>    
    </div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app')

{{-- @section('title', 'Buat Kategori Artikel') --}}
@section('content')
    <div class="container">
        <div class="card mt-4">
            <div class="card-header">
                <div class="text-center">Kategori Artikel</div>    
            </div>
            <div class="card-body">
                <a href="{{route('category.create')}}" class="btn btn-primary">Buat Kategori</a>
                <div class="text-center"><h4>List Kategori</h4></div>
                <table class="table table-bordered table-hover table-striped" id="data-table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Kategori</th>
                            <th>Tanggal Edit</th>
                            <th>Opsi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php
                            $i=1
                        @endphp
                        @foreach($category as $c)
                            <tr>
                                <td>{{$i++}}</td>
                                <td>{{$c->name}}</td>
                                <td>{{date('j F Y', strtotime($c->updated_at))}}</td>
                                <td>
                                    <a href="{{route('category.edit', $c->id)}}" class="btn btn-primary"><i class="fa fa-edit"></i> Edit</a>
                                    <a href="{{route('category.hapus', $c->id)}}" class="btn btn-danger"><i class="fa fa-edit"></i> Hapus</a>
                                    {{-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editModal">
                                        <i class="fa fa-edit"></i> Edit
                                    </button>
                                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#hapusModal">
                                        <i class="fa fa-trash"></i> Hapus
                                    </button> --}}
                                </td>
                            </tr>
                        @endforeach   
                    </tbody>
                </table>
            </div>    
        </div>    
    </div>
@endsection