routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['web', 'auth'])->group(function () {

	Route::get('profile', 'ProfileController@show')->name('profile');
	Route::put('profile', 'ProfileController@update');
	Route::get('profile/edit', 'ProfileController@edit');
	Route::delete('profile/image', 'ProfileController@remove');

	Route::get('account', 'AccountController@show')->name('account');
	Route::put('account', 'AccountController@update');
	Route::get('account/delete', 'AccountController@delete');
	Route::delete('account/delete', 'AccountController@destroy');
});

//Artikel
Route::resource('posts', 'PostController');
Route::get('posts/hapus/{id}', 'PostController@destroy')->name('posts.hapus');

//Kategori
Route::resource('category', 'CategoryController');
Route::get('/category/hapus/{id}', 'CategoryController@destroy')->name('category.hapus');

//Tags
Route::resource('tags', 'TagController');
Route::get('/tags/hapus/{id}', 'TagController@destroy')->name('tags.hapus');

resources/views/blog/create.blade.php
@extends('layouts.app')

@section('title', 'Buat Artikel')
@section('content')
    <div class="container">
        <div class="card mt-4">
            <div class="card-header">
                <div class="text-center">Buat Artikel Baru</div>    
            </div>
            <div class="card-body">
                <form action="{{route('posts.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="title">Judul Artikel</label>
                        <input type="text" name="title" class="form-control" placeholder="Judul Artikel...">
                        {{-- validator --}}
                        @if($errors->has('title'))
                            <div class="text-danger">
                                {{$errors->first('title')}}
                            </div>
                        @endif
                        <label for="category">Kategori</label>
                        <select name="category_id" id="" class="form-control">
                            <option value="" class="disable selected">Pilih Kategori</option>
                            @foreach ($category as $c)
                                <option value="{{$c->id}}">{{$c->name}}</option>
                            @endforeach
                        </select>
                        {{-- validator --}}
                        @if($errors->has('category_id'))
                            <div class="text-danger">
                                {{$errors->first('category_id')}}
                            </div>
                        @endif
                        {{-- Masih belum bisa muncul wkwkwk --}}
                        {{-- <label for="tags">Tag</label>
                        <select name="tags[]" id=""  class="form-control select2" multiple="">
                            @foreach ($tags as $t)
                                <option value="{{$t->id}}">{{$t->name}}</option>
                            @endforeach
                        </select> --}}
                        <label for="image">Gambar</label>
                        <input type="file" name="image" class="form-control">
                        <label for="content">Konten</label>
                        <textarea name="content" class="form-control" placeholder="Konten Artikel..."></textarea>
                        {{-- validator --}}
                        @if($errors->has('content'))
                            <div class="text-danger">
                                {{$errors->first('content')}}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-success" value="Simpan">
                    </div>
                </form>
            </div>    
        </div>    
    </div>   
@endsection

{{-- Kok belum bisa muncul wkwk --}}
{{-- @section('js')
    <script>
        CKEDITOR.replace( 'content' );
    </script>
@endsection --}}

resources/views/blog/edit.blade.php
@extends('layouts.app')

{{-- @section('title', 'Edit Artikel') --}}
@section('content')
    <div class="container">
        <div class="card mt-4">
            <div class="card-header">
                <div class="text-center">Edit Artikel Baru</div>    
            </div>
            <div class="card-body">
                <form action="{{route('posts.update', $posts->id)}}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="title">Judul Artikel</label>
                        <input type="text" name="title" class="form-control" value="{{$posts->title}}" placeholder="Judul Artikel...">
                        {{-- validator --}}
                        @if($errors->has('title'))
                            <div class="text-danger">
                                {{$errors->first('title')}}
                            </div>
                        @endif
                        <select name="category_id" id="" class="form-control">
                            @foreach ($category as $c)
                                <option value="{{$c->id}}" {{ $c->id == $posts->category_id ? 'selected' : '' }}>{{$c->name}}</option>
                            @endforeach
                        </select>
                        <label for="content">Konten</label>
                        <textarea name="content" class="form-control" placeholder="Konten Artikel...">{{$posts->content}}</textarea>
                        {{-- validator --}}
                        @if($errors->has('title'))
                            <div class="text-danger">
                                {{$errors->first('title')}}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-success" value="Simpan">
                    </div>
                </form>
            </div>    
        </div>    
    </div>    
@endsection

resources/views/blog/index.blade.php
@extends('layouts.app')

@section('title', 'Buat Artikel')
@section('content')
    <div class="container">
        <div class="card mt-4">
            <div class="card-header">
                <div class="text-center">Artikel</div>    
            </div>
            <div class="card-body">
                <a href="{{route('posts.create')}}" class="btn btn-primary">Buat Artikel</a>
                <div class="text-center"><h4>List Artikel</h4></div>
                <table class="table table-bordered table-hover table-striped">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Judul Artikel</th>
                            <th>Konten Artikel</th>
                            <th>Kategori</th>
                            <th>Opsi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php
                            $i=1
                        @endphp
                        @foreach($posts as $p)
                            <tr>
                                <td>{{$i++}}</td>
                                <td>{{$p->title}}</td>
                                <td>{{$p->content}}</td>
                                <td>{{$p->categories['name']}}</td>
                                <td>
                                    <a href="{{route('posts.edit', $p->id)}}" class="btn btn-primary"><i class="fa fa-edit"></i> Edit</a>
                                    <a href="{{route('posts.hapus', $p->id)}}" class="btn btn-danger"><i class="fa fa-trash"></i> Hapus</a>
                                </td>
                            </tr>
                        @endforeach   
                    </tbody>
                </table>    
            </div>    
        </div>    
    </div>    
@endsection